const LIMITS = {
  activeGoal: 2500,
  decisions: 9000,
  previousSummary: 2000,
  olderContextTail: 3500,
  fileOperations: 1000,
};

function bounded(value, limit, tail = false) {
  const text = String(value ?? "").trim();
  if (text.length <= limit) return text;
  if (tail) return `[earlier content omitted]\n${text.slice(-limit)}`;
  return `${text.slice(0, limit)}\n[later content omitted]`;
}

function boundedHeadAndTail(value, limit) {
  const text = String(value ?? "").trim();
  if (text.length <= limit) return text;
  const marker = "\n[middle content omitted]\n";
  const available = Math.max(0, limit - marker.length);
  const headLength = Math.ceil(available * 0.6);
  const tailLength = available - headLength;
  return `${text.slice(0, headLength)}${marker}${text.slice(-tailLength)}`;
}

export function buildLoopCompaction({
  activeGoal,
  decisions,
  previousSummary,
  olderContext,
  fileOperations,
  activeSkill,
}) {
  return [
    "# Durable loop continuity",
    "",
    "This structured summary was generated by the isolated Pi pilot extension.",
    "The append-only session JSONL remains the authoritative full history.",
    "",
    "## Active skill",
    bounded(activeSkill || "No interactive Pi skill recorded", 256),
    "",
    "## Active goal and stop condition",
    boundedHeadAndTail(
      activeGoal || "No .working/ACTIVE_GOAL.md record found",
      LIMITS.activeGoal,
    ),
    "",
    "## Settled decisions, exclusions, verification, and manual gates",
    bounded(decisions || "No matching decisions record found", LIMITS.decisions),
    "",
    "## Previous compaction continuity",
    bounded(previousSummary || "None", LIMITS.previousSummary, true),
    "",
    "## Older conversation tail",
    bounded(olderContext || "None", LIMITS.olderContextTail, true),
    "",
    "## Recorded file operations",
    bounded(fileOperations || "None", LIMITS.fileOperations, true),
  ].join("\n");
}
