#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'magenta'
    template = '{{ .UserName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'blue'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'black'
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<#FFAFD7>*</>{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_ahead_icon = '<#88C0D0>⇡ </>'
      branch_behind_icon = '<#88C0D0>⇣ </>'
      branch_icon = ''
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ''

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#A3BE8C'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#B48EAD'
    foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']
    template = '❯ '

    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']
  background = 'transparent'
  template = '❯ '
