#!/usr/bin/env fish

set --local package_dir (path resolve (path dirname (status filename))/..)
set --local repo_dir (path resolve $package_dir/..)

# Match interactive Fish's deterministic basedirs even when this maintenance
# command is launched from a parent shell exporting legacy XDG locations.
set -gx XDG_CONFIG_HOME $HOME/.config
set -gx XDG_DATA_HOME $HOME/.local/share
set -gx XDG_STATE_HOME $HOME/.local/state
set -gx XDG_CACHE_HOME $HOME/.cache
set --local cache_dir $XDG_CACHE_HOME/fish

function __dotfiles_refresh_fail --argument-names label
    for temporary_path in $argv[2..-1]
        command rm -f -- $temporary_path
    end
    echo "Fish startup maintenance: FAIL ($label)" >&2
    exit 1
end

mkdir -p $XDG_CONFIG_HOME $XDG_DATA_HOME $XDG_STATE_HOME $XDG_CACHE_HOME $cache_dir
or __dotfiles_refresh_fail 'create XDG directories'

set --local brew
if test -x /opt/homebrew/bin/brew
    set brew /opt/homebrew/bin/brew
else if test -x /usr/local/bin/brew
    set brew /usr/local/bin/brew
else if test -x /home/linuxbrew/.linuxbrew/bin/brew
    set brew /home/linuxbrew/.linuxbrew/bin/brew
end
if test -n "$brew"
    set --local brew_cache (mktemp "$cache_dir/brew_init.fish.XXXXXX")
    $brew shellenv >$brew_cache
    or __dotfiles_refresh_fail 'brew shellenv' $brew_cache
    test -s $brew_cache
    or __dotfiles_refresh_fail 'empty brew shellenv' $brew_cache
    command mv -- $brew_cache $cache_dir/brew_init.fish
    or __dotfiles_refresh_fail 'install brew cache' $brew_cache
end

if command -q fzf
    set --local fzf_completion_cache (mktemp "$cache_dir/fzf_completion.fish.XXXXXX")
    fzf --fish | awk '/^### completion\.fish ###/{emit=1} emit' >$fzf_completion_cache
    set --local fzf_pipeline_status $pipestatus
    if test $fzf_pipeline_status[1] -ne 0
        __dotfiles_refresh_fail 'fzf --fish' $fzf_completion_cache
    else if test $fzf_pipeline_status[2] -ne 0
        __dotfiles_refresh_fail 'filter fzf completion' $fzf_completion_cache
    else if not test -s $fzf_completion_cache
        __dotfiles_refresh_fail 'empty fzf completion' $fzf_completion_cache
    end
    command mv -- $fzf_completion_cache $cache_dir/fzf_completion.fish
    or __dotfiles_refresh_fail 'install fzf completion cache' $fzf_completion_cache
end

if command -q zoxide
    set --local zoxide_cache (mktemp "$cache_dir/zoxide_init.fish.XXXXXX")
    zoxide init --cmd cd fish >$zoxide_cache
    or __dotfiles_refresh_fail 'zoxide init' $zoxide_cache
    test -s $zoxide_cache
    or __dotfiles_refresh_fail 'empty zoxide init' $zoxide_cache
    command mv -- $zoxide_cache $cache_dir/zoxide_init.fish
    or __dotfiles_refresh_fail 'install zoxide cache' $zoxide_cache
end

if command -q starship
    set --local starship_cache (mktemp "$cache_dir/starship_init.fish.XXXXXX")
    starship init fish --print-full-init >$starship_cache
    or __dotfiles_refresh_fail 'starship init' $starship_cache
    test -s $starship_cache
    or __dotfiles_refresh_fail 'empty starship init' $starship_cache
    command mv -- $starship_cache $cache_dir/starship_init.fish
    or __dotfiles_refresh_fail 'install starship cache' $starship_cache
end

set --local environment_cache (mktemp "$cache_dir/dotfiles_environment.fish.XXXXXX")
printf '%s\n' '# Generated by fish/scripts/refresh_startup.fish.' >$environment_cache
if test (uname) = Darwin; and test -x /usr/libexec/java_home
    set --local java_home (/usr/libexec/java_home 2>/dev/null)
    if test -d "$java_home"
        printf 'set -g __dotfiles_cached_java_home %s\n' (string escape -- $java_home) >>$environment_cache
    end
end
set --local vivid_theme "$repo_dir/vivid/catppuccin-mocha.yml"
if command -q vivid; and test -r "$vivid_theme"
    set --local vivid_output (vivid generate "$vivid_theme")
    or __dotfiles_refresh_fail 'vivid theme generation' $environment_cache
    test -n "$vivid_output"
    or __dotfiles_refresh_fail 'empty vivid theme' $environment_cache
    printf 'set -g __dotfiles_cached_ls_colors %s\n' (string escape -- $vivid_output) >>$environment_cache
end
command mv -- $environment_cache $cache_dir/dotfiles_environment.fish
or __dotfiles_refresh_fail 'install environment cache' $environment_cache

if not test -e $XDG_CONFIG_HOME/starship.toml; and not test -L $XDG_CONFIG_HOME/starship.toml
    ln -s $repo_dir/starship/starship.toml $XDG_CONFIG_HOME/starship.toml
    or __dotfiles_refresh_fail 'link starship config'
end
if not test -e $XDG_CONFIG_HOME/zellij; and not test -L $XDG_CONFIG_HOME/zellij
    ln -s $repo_dir/zellij $XDG_CONFIG_HOME/zellij
    or __dotfiles_refresh_fail 'link zellij config'
end
set --local lazygit_dir $XDG_CONFIG_HOME/lazygit
if test -d $lazygit_dir; and not test -e $lazygit_dir/config.yml; and not test -L $lazygit_dir/config.yml
    ln -s $repo_dir/lazygit/config.yml $lazygit_dir/config.yml
    or __dotfiles_refresh_fail 'link lazygit config'
end

init_fisher --install; or exit

if not git config --global --get alias.ll >/dev/null 2>&1
    git config --global alias.ll 'log --graph --format="%C(yellow)%h%C(red)%d%C(reset) - %C(bold green)(%ar)%C(reset) %s %C(blue)<%an>%C(reset)"'
    or __dotfiles_refresh_fail 'configure Git alias.ll'
end

echo 'Fish startup maintenance: PASS'
